### ISSUE TITLE
play back recorded sound file

### ISSUE THREAD

**Issue by qjcg** [qjcg/soundapp#23]

**Comment by cesine** [comment]
https://github.com/OpenSourceFieldlinguistics/AndroidFieldDB/blob/master/src/com/github/opensourcefieldlinguistics/fielddb/lessons/ui/DatumDetailFragment.java#L654-664

**Comment by cesine** [comment]
this was done in https://github.com/cesine/soundapp/commit/32b3117f7c7da7a4799fe966679f284036456fd4
