### ISSUE TITLE
apply a simple sound effect (ex: pitch shift, echo) to recorded sound

### ISSUE THREAD

**Issue by qjcg** [qjcg/soundapp#3]

**Comment by qjcg** [comment]
- IntentService
- add service to manifest
- create the class (a-s will generate stubs for you)
- when intentservice finishes, cant be notified by a BroadcastReceiver

**Comment by qjcg** [comment]
Test using [PresetReverb](http://developer.android.com/reference/android/media/audiofx/PresetReverb.html).

**Comment by cesine** [comment]
i finished the package renaming, i will try to debug why the intent service isn't getting called so that it will be ready to continue working on the morning.

**Comment by cesine** [comment]
there is an example of playing audio with an effect here 
http://stackoverflow.com/questions/7617778/android-audio-reverb-sample-app
discussion of applying an effect and saving:
http://stackoverflow.com/questions/13507502/android-audio-effect-on-wav-file-and-save-it
modifying wav in java:
http://www.labbookpages.co.uk/audio/javaWavFiles.html
http://stackoverflow.com/questions/6971043/fmod-read-audio-files-add-effects-and-then-save-the-result-int-to-files

---

http://developer.android.com/reference/android/media/AudioTrack.html
http://mobilengineering.blogspot.it/2012/06/audio-mix-and-record-in-android.html

http://stackoverflow.com/questions/8499042/android-audiorecord-example
