### ISSUE TITLE
Move sound between wear and phone

### ISSUE THREAD

**Issue by cesine** [qjcg/soundapp#9]
https://developer.android.com/training/wearables/data-layer/index.html
http://stackoverflow.com/questions/24595679/how-to-use-dataitem-of-android-wear

**Comment by rz-robsn** [comment]
If you are using the wear emulator, you need to use this command to pair it with your device 

```
adb -d forward tcp:5601 tcp:5601
```

taken from [here](http://developer.android.com/training/wearables/apps/creating.html)
